### ISSUE TITLE
Move to Node LTS in test.yml and package.json (>= v14)

### ISSUE THREAD

**Issue by oscard0m** [octokit/auth-action.js#220]
https://github.com/octokit/auth-action.js/blob/040b5b6c48b4beb4d63d16c44de0217c4f485443/.github/workflows/test.yml#L15-L19

**Comment by oscard0m** [comment]
@wolfy1339 did octoherd script fail when opening a PR here?

**Comment by wolfy1339** [comment]
I haven't done every repo
