### ISSUE TITLE
`GITHUB_ACTION` environment variable is not set

### ISSUE THREAD

**Issue by thisismydesign** [octokit/auth-action.js#76]
Getting this error since 2020.08.03 10:00 PM GMT+2.

```
Error: [@octokit/auth-action] `GITHUB_ACTION` environment variable is not set. @octokit/auth-action is meant to be used in GitHub Actions only.
```

I take it something changed at GitHub's side? Is this something to be addressed by you, GH, or the users?

**Comment by gr2m** [comment]
I’ve reported the issue to GitHub, I’m pretty sure it’s a regression with today’s release of the latest action runner

**Comment by gr2m** [comment]
See https://github.com/actions/runner/issues/635

**Comment by thisismydesign** [comment]
Thanks!

**Comment by thisismydesign** [comment]
Seems to have been resolved
